name: Golang SAST

description: Run GoKart to generate a SAST report of your codebase. Results are published to Github.

inputs:
  report-name:
    description: Override the default report name. This is useful for workflows that output multiple reports.
    required: false
    default: "gokart"
  report-retention-days:
    description: Duration in days to preserve reports.
    required: true
    default: "5"
  working-directory:
    description: Relative path under $GITHUB_WORKSPACE where the root project is located.
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Action context
      id: context
      shell: bash
      run: |
        working_directory=$(realpath ${{ inputs.working-directory }})
        echo "working-directory=$working_directory" >> $GITHUB_OUTPUT
        echo "sarif-file=build/sast/${{ inputs.report-name }}.sarif" >> $GITHUB_OUTPUT

    - name: Install GoKart
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        go install github.com/praetorian-inc/gokart@latest
        command -v asdf >/dev/null 2>&1 && asdf reshim golang

    - name: Generate SAST report
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        mkdir -p build/sast
        gokart scan -s -o ${{ steps.context.outputs.sarif-file }} .

    - uses: actions/upload-artifact@v3
      if: "!cancelled()"
      with:
        name: ${{ inputs.report-name }}.sarif
        path: ${{ steps.context.outputs.working-directory }}/${{ steps.context.outputs.sarif-file }}
        retention-days: ${{ inputs.report-retention-days }}

    - name: Publish report
      uses: github/codeql-action/upload-sarif@v2
      with:
        category: ${{ inputs.report-name }}
        sarif_file: ${{ inputs.working-directory }}/${{ steps.context.outputs.sarif-file }}
